# Generated by Django 3.1.8 on 2022-04-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='image',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
    ]
