# Generated by Django 3.1.8 on 2022-04-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0002_auto_20220418_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
