# Generated by Django 3.1.8 on 2022-04-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
