# Generated by Django 3.1.8 on 2022-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0005_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('emp_id', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
                ('enter', models.DateTimeField(auto_now_add=True)),
                ('exit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
