# Generated by Django 3.1.8 on 2022-04-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0006_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='image',
        ),
    ]
