# Generated by Django 3.1.8 on 2022-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0008_auto_20220430_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
