# Generated by Django 3.1.8 on 2022-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0009_auto_20220430_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
