# Generated by Django 3.1.8 on 2022-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0010_auto_20220430_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidentifiedFaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('enter', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
